#!/usr/bin/env bash

pin=${RESET_PIN:-18}

echo -e "\nautoreset: starting"

if timeout --preserve-status --foreground 5s \
    grep --quiet --max-count=1 -E '.+TIOCM_DTR.+'; then

    echo "autoreset: resetting using GPIO pin ${pin}..."
    gpioset --mode time --usec 5000 gpiochip0 "${pin}=0"
    gpioset --mode time --sec 1 gpiochip0 "${pin}=1"

else
    echo "autoreset: timeout"
fi

echo "autoreset: done"
